<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\ServiceProvider;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ServiceProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $providers = [
            // Photography & Videography
            [
                'user' => [
                    'name' => 'Tiwonge Banda',
                    'email' => 'tiwonge@eventsmalawi.com',
                    'phone' => '+265991234567',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Tiwonge Photography',
                    'slug' => 'tiwonge-photography',
                    'description' => 'Award-winning wedding and event photographer based in Lilongwe. Specializing in capturing authentic moments with a creative eye and professional equipment.',
                    'business_registration_number' => 'BN12345',
                    'location' => 'Area 47',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9626,
                    'longitude' => 33.7741,
                    'phone' => '+265991234567',
                    'email' => 'tiwonge@eventsmalawi.com',
                    'logo' => '/resized-win/wedding-photo-1.jpg',
                    'cover_image' => '/resized-win/bride-groom-shoot-5.jpg',
                    'average_rating' => 4.95,
                    'total_reviews' => 87,
                    'total_bookings' => 124,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(6),
                ],
            ],
            [
                'user' => [
                    'name' => 'Mphatso Chirwa',
                    'email' => 'info@motionvisions.mw',
                    'phone' => '+265999345678',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Motion Visions Videography',
                    'slug' => 'motion-visions-video',
                    'description' => 'Cinematic wedding and event videography. We tell your story through breathtaking visuals and professional editing. Drone coverage available.',
                    'business_registration_number' => 'BN34567',
                    'location' => 'City Centre',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9833,
                    'longitude' => 33.7833,
                    'phone' => '+265999345678',
                    'email' => 'info@motionvisions.mw',
                    'logo' => '/resized-win/videographer-1.jpg',
                    'cover_image' => '/resized-win/bride-groom-photoshoot-1.jpg',
                    'average_rating' => 4.89,
                    'total_reviews' => 52,
                    'total_bookings' => 76,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(4),
                ],
            ],

            // Decor & Styling
            [
                'user' => [
                    'name' => 'Chikondi Phiri',
                    'email' => 'chikondi@elegantdecor.mw',
                    'phone' => '+265888234567',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Elegant Events Décor',
                    'slug' => 'elegant-events-decor',
                    'description' => 'Transform your events into unforgettable experiences with our premium decoration services. From weddings to corporate events, we bring your vision to life.',
                    'business_registration_number' => 'BN23456',
                    'location' => 'Ginnery Corner',
                    'city' => 'Blantyre',
                    'latitude' => -15.7861,
                    'longitude' => 35.0058,
                    'phone' => '+265888234567',
                    'email' => 'chikondi@elegantdecor.mw',
                    'logo' => '/resized-win/decor-1.jpg',
                    'cover_image' => '/resized-win/decor-7.jpg',
                    'average_rating' => 5.0,
                    'total_reviews' => 63,
                    'total_bookings' => 98,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(8),
                ],
            ],
            [
                'user' => [
                    'name' => 'Alinafe Moyo',
                    'email' => 'alinafe@luxurydecor.mw',
                    'phone' => '+265991887766',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Luxury Touch Decor',
                    'slug' => 'luxury-touch-decor',
                    'description' => 'Specializing in luxury wedding and corporate event decorations. Premium quality fabrics, lighting, and custom designs to match your theme.',
                    'business_registration_number' => 'BN78901',
                    'location' => 'Namiwawa',
                    'city' => 'Blantyre',
                    'latitude' => -15.7900,
                    'longitude' => 35.0100,
                    'phone' => '+265991887766',
                    'email' => 'alinafe@luxurydecor.mw',
                    'logo' => '/resized-win/decor-3.jpg',
                    'cover_image' => '/resized-win/decor-5.jpg',
                    'average_rating' => 4.92,
                    'total_reviews' => 45,
                    'total_bookings' => 67,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(5),
                ],
            ],

            // Catering & Food Services
            [
                'user' => [
                    'name' => 'Kondwani Mkandawire',
                    'email' => 'kondwani@gourmetcatering.mw',
                    'phone' => '+265999678901',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Gourmet Gatherings Catering',
                    'slug' => 'gourmet-gatherings',
                    'description' => 'Premium catering services for weddings, corporate events, and private functions. International and local cuisine expertly prepared and beautifully presented.',
                    'business_registration_number' => 'BN67890',
                    'location' => 'Area 43',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9789,
                    'longitude' => 33.7633,
                    'phone' => '+265999678901',
                    'email' => 'kondwani@gourmetcatering.mw',
                    'logo' => '/resized-win/food-1.jpg',
                    'cover_image' => '/resized-win/food-7.jpg',
                    'average_rating' => 4.88,
                    'total_reviews' => 78,
                    'total_bookings' => 115,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(7),
                ],
            ],
            [
                'user' => [
                    'name' => 'Mercy Nyirenda',
                    'email' => 'mercy@traditionalfeast.mw',
                    'phone' => '+265888998877',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Traditional Feast Catering',
                    'slug' => 'traditional-feast',
                    'description' => 'Authentic Malawian traditional cuisine for weddings and cultural events. We specialize in nsima, chambo, and traditional delicacies prepared with love.',
                    'business_registration_number' => 'BN89012',
                    'location' => 'Chichiri',
                    'city' => 'Blantyre',
                    'latitude' => -15.7950,
                    'longitude' => 35.0250,
                    'phone' => '+265888998877',
                    'email' => 'mercy@traditionalfeast.mw',
                    'logo' => '/resized-win/food-3.jpg',
                    'cover_image' => '/resized-win/food-5.jpg',
                    'average_rating' => 4.85,
                    'total_reviews' => 56,
                    'total_bookings' => 89,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(9),
                ],
            ],

            // Bakers & Cake Designers
            [
                'user' => [
                    'name' => 'Tamanda Kachingwe',
                    'email' => 'tamanda@sweetcreations.mw',
                    'phone' => '+265991776655',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Sweet Creations Bakery',
                    'slug' => 'sweet-creations',
                    'description' => 'Custom wedding cakes and desserts. Each cake is a masterpiece, designed and crafted with premium ingredients to make your special day even sweeter.',
                    'business_registration_number' => 'BN90123',
                    'location' => 'Area 3',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9700,
                    'longitude' => 33.7800,
                    'phone' => '+265991776655',
                    'email' => 'tamanda@sweetcreations.mw',
                    'logo' => '/resized-win/cake-1.jpg',
                    'cover_image' => '/resized-win/cake-6.jpg',
                    'average_rating' => 4.98,
                    'total_reviews' => 102,
                    'total_bookings' => 145,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(11),
                ],
            ],

            // Flowers & Plants
            [
                'user' => [
                    'name' => 'Grace Kadzamira',
                    'email' => 'grace@bloomflorists.mw',
                    'phone' => '+265991567890',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Bloom & Petal Florists',
                    'slug' => 'bloom-petal-florists',
                    'description' => 'Exquisite floral arrangements for weddings and special events. Fresh flowers delivered across Malawi. We create stunning bouquets, centerpieces, and floral decor.',
                    'business_registration_number' => 'BN56789',
                    'location' => 'Namiwawa',
                    'city' => 'Blantyre',
                    'latitude' => -15.7869,
                    'longitude' => 35.0031,
                    'phone' => '+265991567890',
                    'email' => 'grace@bloomflorists.mw',
                    'logo' => '/resized-win/decor-2.jpg',
                    'cover_image' => '/resized-win/decor-4.jpg',
                    'average_rating' => 4.97,
                    'total_reviews' => 95,
                    'total_bookings' => 142,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(10),
                ],
            ],

            // Sound & PA Systems
            [
                'user' => [
                    'name' => 'Thokozani Mwale',
                    'email' => 'thoko@crystalsound.mw',
                    'phone' => '+265888456789',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Crystal Sound Systems',
                    'slug' => 'crystal-sound-systems',
                    'description' => 'Professional PA systems and audio equipment rental for all types of events. Quality sound guaranteed with experienced sound engineers available.',
                    'business_registration_number' => 'BN45678',
                    'location' => 'Mzuzu Town',
                    'city' => 'Mzuzu',
                    'latitude' => -11.4587,
                    'longitude' => 34.0209,
                    'phone' => '+265888456789',
                    'email' => 'thoko@crystalsound.mw',
                    'logo' => '/resized-win/pa-system-1.jpg',
                    'cover_image' => '/resized-win/pa-system-4.jpg',
                    'average_rating' => 4.92,
                    'total_reviews' => 41,
                    'total_bookings' => 89,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(5),
                ],
            ],
            [
                'user' => [
                    'name' => 'Yamikani Tembo',
                    'email' => 'yamikani@prosoundmw.com',
                    'phone' => '+265999887766',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'ProSound Malawi',
                    'slug' => 'prosound-malawi',
                    'description' => 'Premium sound and lighting solutions for concerts, weddings, and corporate events. State-of-the-art equipment with professional setup and operation.',
                    'business_registration_number' => 'BN01234',
                    'location' => 'Area 9',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9500,
                    'longitude' => 33.7700,
                    'phone' => '+265999887766',
                    'email' => 'yamikani@prosoundmw.com',
                    'logo' => '/resized-win/pa-system-3.jpg',
                    'cover_image' => '/resized-win/pa-system-7.jpg',
                    'average_rating' => 4.87,
                    'total_reviews' => 38,
                    'total_bookings' => 72,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(3),
                ],
            ],

            // DJs & Entertainment
            [
                'user' => [
                    'name' => 'Limbani Kaunda',
                    'email' => 'dj@spinmaster.mw',
                    'phone' => '+265991665544',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'DJ SpinMaster Entertainment',
                    'slug' => 'dj-spinmaster',
                    'description' => 'Professional DJ services for weddings, parties, and corporate events. Extensive music library covering all genres. We keep your guests dancing all night!',
                    'business_registration_number' => 'BN12346',
                    'location' => 'Ndirande',
                    'city' => 'Blantyre',
                    'latitude' => -15.8100,
                    'longitude' => 35.0300,
                    'phone' => '+265991665544',
                    'email' => 'dj@spinmaster.mw',
                    'logo' => '/resized-win/dj-1.jpg',
                    'cover_image' => '/resized-win/lighting-1.jpg',
                    'average_rating' => 4.90,
                    'total_reviews' => 68,
                    'total_bookings' => 103,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(6),
                ],
            ],

            // MCs & Hosts
            [
                'user' => [
                    'name' => 'Chifundo Matemba',
                    'email' => 'chifundo@mcpro.mw',
                    'phone' => '+265888554433',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'MC Chifundo - Professional Host',
                    'slug' => 'mc-chifundo',
                    'description' => 'Experienced MC for weddings, corporate events, and conferences. Bilingual (English/Chichewa) with excellent crowd engagement skills.',
                    'business_registration_number' => 'BN23457',
                    'location' => 'City Centre',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9850,
                    'longitude' => 33.7850,
                    'phone' => '+265888554433',
                    'email' => 'chifundo@mcpro.mw',
                    'logo' => '/resized-win/mc-1.jpg',
                    'cover_image' => '/resized-win/mc-3.jpg',
                    'average_rating' => 4.93,
                    'total_reviews' => 75,
                    'total_bookings' => 118,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(8),
                ],
            ],

            // Tents & Marquees
            [
                'user' => [
                    'name' => 'Patrick Nkhoma',
                    'email' => 'patrick@royaltents.mw',
                    'phone' => '+265999443322',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Royal Tents & Marquees',
                    'slug' => 'royal-tents',
                    'description' => 'High-quality tent and marquee rentals for outdoor events. Various sizes available. Complete setup and takedown services included.',
                    'business_registration_number' => 'BN34568',
                    'location' => 'Kameza',
                    'city' => 'Blantyre',
                    'latitude' => -15.7750,
                    'longitude' => 35.0150,
                    'phone' => '+265999443322',
                    'email' => 'patrick@royaltents.mw',
                    'logo' => '/resized-win/tent-1.jpg',
                    'cover_image' => '/resized-win/tent-decor.jpg',
                    'average_rating' => 4.86,
                    'total_reviews' => 49,
                    'total_bookings' => 81,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(4),
                ],
            ],

            // Venues
            [
                'user' => [
                    'name' => 'Stella Banda',
                    'email' => 'info@sunsetgarden.mw',
                    'phone' => '+265991332211',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Sunset Garden Venue',
                    'slug' => 'sunset-garden-venue',
                    'description' => 'Beautiful outdoor garden venue perfect for weddings and receptions. Capacity up to 500 guests. Stunning sunset views and professional catering facilities.',
                    'business_registration_number' => 'BN45679',
                    'location' => 'Area 47',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9600,
                    'longitude' => 33.7750,
                    'phone' => '+265991332211',
                    'email' => 'info@sunsetgarden.mw',
                    'logo' => '/resized-win/venue-1.jpg',
                    'cover_image' => '/resized-win/venue-5.jpg',
                    'average_rating' => 4.94,
                    'total_reviews' => 82,
                    'total_bookings' => 96,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(12),
                ],
            ],

            // Chairs & Tables Rental
            [
                'user' => [
                    'name' => 'Isaac Phiri',
                    'email' => 'isaac@premiumrentals.mw',
                    'phone' => '+265888221100',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Premium Event Rentals',
                    'slug' => 'premium-event-rentals',
                    'description' => 'Complete event rental solutions - chairs, tables, cutlery, glassware, and decor items. Competitive prices and reliable service.',
                    'business_registration_number' => 'BN56780',
                    'location' => 'Mchesi',
                    'city' => 'Blantyre',
                    'latitude' => -15.7800,
                    'longitude' => 35.0200,
                    'phone' => '+265888221100',
                    'email' => 'isaac@premiumrentals.mw',
                    'logo' => '/resized-win/umbrella-chairs-tents-1.jpg',
                    'cover_image' => '/resized-win/tent-3.jpg',
                    'average_rating' => 4.81,
                    'total_reviews' => 37,
                    'total_bookings' => 94,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(7),
                ],
            ],

            // Wedding Planners
            [
                'user' => [
                    'name' => 'Precious Mkwanda',
                    'email' => 'precious@dreamweddings.mw',
                    'phone' => '+265999110099',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Dream Weddings Malawi',
                    'slug' => 'dream-weddings',
                    'description' => 'Full-service wedding planning and coordination. From concept to execution, we handle every detail to create your perfect day.',
                    'business_registration_number' => 'BN67891',
                    'location' => 'Area 10',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9650,
                    'longitude' => 33.7900,
                    'phone' => '+265999110099',
                    'email' => 'precious@dreamweddings.mw',
                    'logo' => '/resized-win/bridal-party-shoot-1.jpg',
                    'cover_image' => '/resized-win/bride-groom-shoot-2.jpg',
                    'average_rating' => 4.96,
                    'total_reviews' => 91,
                    'total_bookings' => 108,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(9),
                ],
            ],

            // Bridal Wear
            [
                'user' => [
                    'name' => 'Linda Nyirongo',
                    'email' => 'linda@bridalelegance.mw',
                    'phone' => '+265991009988',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Bridal Elegance Boutique',
                    'slug' => 'bridal-elegance',
                    'description' => 'Exclusive bridal gowns and bridesmaid dresses. Custom designs and alterations available. Make your wedding dress dreams come true.',
                    'business_registration_number' => 'BN78902',
                    'location' => 'Victoria Avenue',
                    'city' => 'Blantyre',
                    'latitude' => -15.7880,
                    'longitude' => 35.0050,
                    'phone' => '+265991009988',
                    'email' => 'linda@bridalelegance.mw',
                    'logo' => '/resized-win/bridal-party-clothes-1.jpg',
                    'cover_image' => '/resized-win/bride-groom-shoot-3.jpg',
                    'average_rating' => 4.91,
                    'total_reviews' => 67,
                    'total_bookings' => 85,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(6),
                ],
            ],

            // Groom Wear
            [
                'user' => [
                    'name' => 'James Lungu',
                    'email' => 'james@gentlemansuits.mw',
                    'phone' => '+265888998866',
                    'password' => Hash::make('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'The Gentleman\'s Wardrobe',
                    'slug' => 'gentlemans-wardrobe',
                    'description' => 'Premium suits and formal wear for grooms and groomsmen. Sales and rentals available. Custom tailoring services for the perfect fit.',
                    'business_registration_number' => 'BN89013',
                    'location' => 'Crossroads',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9700,
                    'longitude' => 33.7650,
                    'phone' => '+265888998866',
                    'email' => 'james@gentlemansuits.mw',
                    'logo' => '/resized-win/groom-men-shoot.jpg',
                    'cover_image' => '/resized-win/groomsmen-shoot-1.jpg',
                    'average_rating' => 4.84,
                    'total_reviews' => 54,
                    'total_bookings' => 79,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(5),
                ],
            ],
        ];

        foreach ($providers as $providerData) {
            $user = User::create($providerData['user']);
            $provider = $user->serviceProvider()->create($providerData['provider']);
        }

        $this->command->info('Service providers seeded successfully!');
    }
}
