<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServiceProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $providers = [
            [
                'user' => [
                    'name' => 'Tiwonge Banda',
                    'email' => 'tiwonge@eventsmalawi.com',
                    'phone' => '+265991234567',
                    'password' => bcrypt('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Tiwonge Photography',
                    'slug' => 'tiwonge-photography',
                    'description' => 'Award-winning wedding and event photographer based in Lilongwe. Specializing in capturing authentic moments with a creative eye.',
                    'business_registration_number' => 'BN12345',
                    'location' => 'Area 47',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9626,
                    'longitude' => 33.7741,
                    'phone' => '+265991234567',
                    'email' => 'tiwonge@eventsmalawi.com',
                    'logo' => '/professional-photographer-portfolio-wedding.jpg',
                    'cover_image' => '/professional-event-photographer-with-camera.jpg',
                    'average_rating' => 4.95,
                    'total_reviews' => 87,
                    'total_bookings' => 124,
                    'is_verified' => true,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(6),
                ],
            ],
            [
                'user' => [
                    'name' => 'Chikondi Phiri',
                    'email' => 'chikondi@elegantdecor.mw',
                    'phone' => '+265888234567',
                    'password' => bcrypt('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Elegant Events Décor',
                    'slug' => 'elegant-events-decor',
                    'description' => 'Transform your events into unforgettable experiences with our premium decoration services. From weddings to corporate events.',
                    'business_registration_number' => 'BN23456',
                    'location' => 'Ginnery Corner',
                    'city' => 'Blantyre',
                    'latitude' => -15.7861,
                    'longitude' => 35.0058,
                    'phone' => '+265888234567',
                    'email' => 'chikondi@elegantdecor.mw',
                    'logo' => '/luxury-wedding-decoration-flowers.jpg',
                    'cover_image' => '/elegant-event-decoration-setup.jpg',
                    'average_rating' => 5.0,
                    'total_reviews' => 63,
                    'total_bookings' => 98,
                    'is_verified' => true,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(8),
                ],
            ],
            [
                'user' => [
                    'name' => 'Mphatso Chirwa',
                    'email' => 'info@motionvisions.mw',
                    'phone' => '+265999345678',
                    'password' => bcrypt('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Motion Visions Videography',
                    'slug' => 'motion-visions-video',
                    'description' => 'Cinematic wedding and event videography. We tell your story through breathtaking visuals and professional editing.',
                    'business_registration_number' => 'BN34567',
                    'location' => 'City Centre',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9833,
                    'longitude' => 33.7833,
                    'phone' => '+265999345678',
                    'email' => 'info@motionvisions.mw',
                    'logo' => '/cinematic-wedding-videography.jpg',
                    'cover_image' => '/videographer-filming-wedding-event.jpg',
                    'average_rating' => 4.89,
                    'total_reviews' => 52,
                    'total_bookings' => 76,
                    'is_verified' => true,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(4),
                ],
            ],
            [
                'user' => [
                    'name' => 'Thokozani Mwale',
                    'email' => 'thoko@crystalsound.mw',
                    'phone' => '+265888456789',
                    'password' => bcrypt('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Crystal Sound Systems',
                    'slug' => 'crystal-sound-systems',
                    'description' => 'Professional PA systems and audio equipment rental for all types of events. Quality sound guaranteed.',
                    'business_registration_number' => 'BN45678',
                    'location' => 'Mzuzu Town',
                    'city' => 'Mzuzu',
                    'latitude' => -11.4587,
                    'longitude' => 34.0209,
                    'phone' => '+265888456789',
                    'email' => 'thoko@crystalsound.mw',
                    'logo' => '/professional-audio-equipment-event.jpg',
                    'cover_image' => '/professional-sound-system-event-setup.jpg',
                    'average_rating' => 4.92,
                    'total_reviews' => 41,
                    'total_bookings' => 89,
                    'is_verified' => true,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(5),
                ],
            ],
            [
                'user' => [
                    'name' => 'Grace Kadzamira',
                    'email' => 'grace@bloomflorists.mw',
                    'phone' => '+265991567890',
                    'password' => bcrypt('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Bloom & Petal Florists',
                    'slug' => 'bloom-petal-florists',
                    'description' => 'Exquisite floral arrangements for weddings and special events. Fresh flowers delivered across Malawi.',
                    'business_registration_number' => 'BN56789',
                    'location' => 'Namiwawa',
                    'city' => 'Blantyre',
                    'latitude' => -15.7869,
                    'longitude' => 35.0031,
                    'phone' => '+265991567890',
                    'email' => 'grace@bloomflorists.mw',
                    'logo' => '/luxury-wedding-flowers-bouquet.jpg',
                    'cover_image' => '/elegant-floral-arrangements.jpg',
                    'average_rating' => 4.97,
                    'total_reviews' => 95,
                    'total_bookings' => 142,
                    'is_verified' => true,
                    'is_featured' => true,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(10),
                ],
            ],
            [
                'user' => [
                    'name' => 'Kondwani Mkandawire',
                    'email' => 'kondwani@gourmetcatering.mw',
                    'phone' => '+265999678901',
                    'password' => bcrypt('password'),
                    'role' => 'provider',
                    'is_verified' => true,
                    'email_verified_at' => now(),
                ],
                'provider' => [
                    'business_name' => 'Gourmet Gatherings Catering',
                    'slug' => 'gourmet-gatherings',
                    'description' => 'Premium catering services for weddings, corporate events, and private functions. International and local cuisine.',
                    'business_registration_number' => 'BN67890',
                    'location' => 'Area 43',
                    'city' => 'Lilongwe',
                    'latitude' => -13.9789,
                    'longitude' => 33.7633,
                    'phone' => '+265999678901',
                    'email' => 'kondwani@gourmetcatering.mw',
                    'logo' => '/elegant-catering-food-display.jpg',
                    'cover_image' => '/professional-catering-service.jpg',
                    'average_rating' => 4.88,
                    'total_reviews' => 78,
                    'total_bookings' => 115,
                    'is_verified' => true,
                    'is_featured' => false,
                    'is_active' => true,
                    'verification_status' => 'approved',
                    'verified_at' => now()->subMonths(7),
                ],
            ],
        ];

        foreach ($providers as $providerData) {
            $user = \App\User::create($providerData['user']);
            $provider = $user->serviceProvider()->create($providerData['provider']);
        }
    }
}
