import { Head, Link } from '@inertiajs/react'
import ProviderLayout from '@/Components/ProviderLayout'
import DateRangeSelector from '@/Components/Analytics/DateRangeSelector'
import ServiceBarChart from '@/Components/Analytics/ServiceBarChart'
import StatusPieChart from '@/Components/Analytics/StatusPieChart'
import { Button } from '@/Components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/Components/ui/card'
import { Badge } from '@/Components/ui/badge'
import { ArrowLeft, TrendingUp, TrendingDown, Minus } from 'lucide-react'

interface DateRange {
  start_date: string
  end_date: string
}

interface ServicePerformance {
  id: number
  name: string
  base_price: number
  is_active: boolean
  total_bookings: number
  revenue: number
  conversion_rate: number
  cancellation_rate: number
}

interface RevenueContribution {
  name: string
  value: number
}

interface Props {
  dateRange: DateRange
  service_performance: ServicePerformance[]
  revenue_contribution: RevenueContribution[]
  currency: string
}

export default function ServicesAnalytics({
  dateRange,
  service_performance,
  revenue_contribution,
  currency,
}: Props) {
  function getTrendIcon(rate: number, goodHigh: boolean = true) {
    if (rate === 0) return <Minus className="h-4 w-4 text-muted-foreground" />
    const isGood = goodHigh ? rate > 50 : rate < 20
    if (isGood) {
      return <TrendingUp className="h-4 w-4 text-green-600" />
    }
    return <TrendingDown className="h-4 w-4 text-red-600" />
  }

  const topService = service_performance.length > 0
    ? service_performance.reduce((max, service) => service.revenue > max.revenue ? service : max, service_performance[0])
    : null

  const totalRevenue = service_performance.reduce((sum, service) => sum + service.revenue, 0)

  return (
    <ProviderLayout title="Service Analytics">
      <Head title="Service Analytics" />

      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="outline" size="sm" asChild>
              <Link href="/provider/analytics">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Link>
            </Button>
            <div>
              <h1 className="text-3xl font-bold">Service Performance</h1>
              <p className="text-muted-foreground mt-1">
                Compare and analyze service metrics
              </p>
            </div>
          </div>
        </div>

        {/* Date Range Selector */}
        <DateRangeSelector
          startDate={dateRange.start_date}
          endDate={dateRange.end_date}
        />

        {/* Top Service Highlight */}
        {topService && (
          <Card className="bg-gradient-to-r from-primary/10 to-primary/5">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-1">Top Performing Service</p>
                  <h2 className="text-2xl font-bold mb-2">{topService.name}</h2>
                  <div className="flex gap-4">
                    <div>
                      <p className="text-sm text-muted-foreground">Revenue</p>
                      <p className="font-semibold">{currency} {topService.revenue.toLocaleString()}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Bookings</p>
                      <p className="font-semibold">{topService.total_bookings}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Conversion</p>
                      <p className="font-semibold">{topService.conversion_rate}%</p>
                    </div>
                  </div>
                </div>
                <Badge variant="default" className="text-lg px-4 py-2">
                  {totalRevenue > 0 ? ((topService.revenue / totalRevenue) * 100).toFixed(1) : 0}% of total revenue
                </Badge>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Charts */}
        <div className="grid gap-6 md:grid-cols-2">
          {/* Revenue Comparison */}
          <ServiceBarChart
            data={service_performance}
            title="Revenue Comparison"
            description="Revenue generated by each service"
            currency={currency}
            showRevenue
            showBookings={false}
          />

          {/* Revenue Contribution Pie */}
          {revenue_contribution.length > 0 && (
            <StatusPieChart
              data={revenue_contribution}
              title="Revenue Contribution"
              description="Percentage of total revenue per service"
              valueKey="value"
            />
          )}
        </div>

        {/* Bookings Comparison */}
        <ServiceBarChart
          data={service_performance}
          title="Booking Volume Comparison"
          description="Number of bookings per service"
          currency={currency}
          showRevenue={false}
          showBookings
        />

        {/* Service Performance Table */}
        <Card>
          <CardHeader>
            <CardTitle>Detailed Service Metrics</CardTitle>
            <CardDescription>Complete performance breakdown for all services</CardDescription>
          </CardHeader>
          <CardContent>
            {service_performance.length > 0 ? (
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-muted/50">
                    <tr>
                      <th className="px-4 py-3 text-left text-sm font-medium">Service</th>
                      <th className="px-4 py-3 text-right text-sm font-medium">Base Price</th>
                      <th className="px-4 py-3 text-right text-sm font-medium">Bookings</th>
                      <th className="px-4 py-3 text-right text-sm font-medium">Revenue</th>
                      <th className="px-4 py-3 text-center text-sm font-medium">Conversion</th>
                      <th className="px-4 py-3 text-center text-sm font-medium">Cancellation</th>
                      <th className="px-4 py-3 text-center text-sm font-medium">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {service_performance.map((service) => (
                      <tr key={service.id} className="hover:bg-muted/50">
                        <td className="px-4 py-3">
                          <div>
                            <p className="font-medium">{service.name}</p>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-right text-muted-foreground">
                          {currency} {service.base_price.toLocaleString()}
                        </td>
                        <td className="px-4 py-3 text-right font-medium">
                          {service.total_bookings}
                        </td>
                        <td className="px-4 py-3 text-right font-semibold">
                          {currency} {service.revenue.toLocaleString()}
                        </td>
                        <td className="px-4 py-3">
                          <div className="flex items-center justify-center gap-2">
                            {getTrendIcon(service.conversion_rate, true)}
                            <span className={service.conversion_rate >= 50 ? 'text-green-600' : service.conversion_rate >= 30 ? 'text-yellow-600' : 'text-red-600'}>
                              {service.conversion_rate}%
                            </span>
                          </div>
                        </td>
                        <td className="px-4 py-3">
                          <div className="flex items-center justify-center gap-2">
                            {getTrendIcon(service.cancellation_rate, false)}
                            <span className={service.cancellation_rate <= 10 ? 'text-green-600' : service.cancellation_rate <= 20 ? 'text-yellow-600' : 'text-red-600'}>
                              {service.cancellation_rate}%
                            </span>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-center">
                          <Badge variant={service.is_active ? 'default' : 'secondary'}>
                            {service.is_active ? 'Active' : 'Inactive'}
                          </Badge>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot className="bg-muted/50 font-semibold">
                    <tr>
                      <td className="px-4 py-3" colSpan={2}>Total</td>
                      <td className="px-4 py-3 text-right">
                        {service_performance.reduce((sum, s) => sum + s.total_bookings, 0)}
                      </td>
                      <td className="px-4 py-3 text-right">
                        {currency} {service_performance.reduce((sum, s) => sum + s.revenue, 0).toLocaleString()}
                      </td>
                      <td className="px-4 py-3 text-center">
                        {service_performance.length > 0
                          ? (service_performance.reduce((sum, s) => sum + s.conversion_rate, 0) / service_performance.length).toFixed(1)
                          : 0}%
                      </td>
                      <td className="px-4 py-3 text-center">
                        {service_performance.length > 0
                          ? (service_performance.reduce((sum, s) => sum + s.cancellation_rate, 0) / service_performance.length).toFixed(1)
                          : 0}%
                      </td>
                      <td className="px-4 py-3 text-center">-</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            ) : (
              <p className="text-center text-muted-foreground py-8">
                No service data available for this period
              </p>
            )}
          </CardContent>
        </Card>

        {/* Key Insights */}
        {service_performance.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Service Insights</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <div className="w-2 h-2 rounded-full bg-primary mt-2" />
                  <div>
                    <p className="font-medium">Best Converter</p>
                    <p className="text-sm text-muted-foreground">
                      {service_performance.reduce((max, service) =>
                        service.conversion_rate > max.conversion_rate ? service : max, service_performance[0]
                      ).name} has the highest conversion rate at{' '}
                      {service_performance.reduce((max, service) =>
                        service.conversion_rate > max.conversion_rate ? service : max, service_performance[0]
                      ).conversion_rate}%
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-2 h-2 rounded-full bg-primary mt-2" />
                  <div>
                    <p className="font-medium">Most Popular</p>
                    <p className="text-sm text-muted-foreground">
                      {service_performance.reduce((max, service) =>
                        service.total_bookings > max.total_bookings ? service : max, service_performance[0]
                      ).name} has the most bookings with{' '}
                      {service_performance.reduce((max, service) =>
                        service.total_bookings > max.total_bookings ? service : max, service_performance[0]
                      ).total_bookings} total
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-2 h-2 rounded-full bg-primary mt-2" />
                  <div>
                    <p className="font-medium">Revenue Leader</p>
                    <p className="text-sm text-muted-foreground">
                      {topService?.name} generates the most revenue at{' '}
                      {currency} {topService?.revenue.toLocaleString()}
                      {' '}({totalRevenue > 0 ? ((topService!.revenue / totalRevenue) * 100).toFixed(1) : 0}% of total)
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </ProviderLayout>
  )
}
